"""Add column scheduled_inquiries to Schedule model

Revision ID: 313b29d9764f
Revises: 84e8da72bf09
Create Date: 2024-12-02 17:05:47.707128

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "313b29d9764f"
down_revision = "84e8da72bf09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule",
        sa.Column(
            "scheduled_inquiries", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.execute("UPDATE \"schedule\" SET scheduled_inquiries = '[]'")
    op.alter_column("schedule", "scheduled_inquiries", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "scheduled_inquiries")
    # ### end Alembic commands ###
