"""Add created_at column to Inquiry table

Revision ID: 58b1e133fb7a
Revises: 1617c0338835
Create Date: 2024-09-16 03:37:08.600997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b1e133fb7a'
down_revision = '1617c0338835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiry', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inquiry', 'created_at')
    # ### end Alembic commands ###
