"""change maxlen inquiry

Revision ID: 6c01e8a810c5
Revises: 58b1e133fb7a
Create Date: 2024-09-20 12:54:22.433475

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6c01e8a810c5"
down_revision = "58b1e133fb7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inquiry",
        "text",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.VARCHAR(length=256),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inquiry",
        "text",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
