"""Add unique constraint on inquiry_id to ScheduledInquiry model

Revision ID: 84e8da72bf09
Revises: d64a4e1708bd
Create Date: 2024-11-29 07:53:08.613606

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '84e8da72bf09'
down_revision = 'd64a4e1708bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'scheduledinquiry', ['inquiry_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduledinquiry', type_='unique')
    # ### end Alembic commands ###
