"""Add column theme_id to Inquiry model

Revision ID: d64a4e1708bd
Revises: 828527f72c54
Create Date: 2024-11-26 05:15:15.016183

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd64a4e1708bd'
down_revision = '828527f72c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiry', sa.Column('theme_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inquiry', 'theme', ['theme_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inquiry', type_='foreignkey')
    op.drop_column('inquiry', 'theme_id')
    # ### end Alembic commands ###
