"""Remove ScheduledInquiry model

Revision ID: f013bcca5e90
Revises: 72072e9463ae
Create Date: 2024-12-02 18:31:15.803622

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "f013bcca5e90"
down_revision = "72072e9463ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scheduledinquiry")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduledinquiry",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("inquiry_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("rank", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["inquiry_id"],
            ["inquiry.id"],
            name="scheduledinquiry_inquiry_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="scheduledinquiry_pkey"),
        sa.UniqueConstraint("inquiry_id", name="scheduledinquiry_inquiry_id_key"),
    )
    # ### end Alembic commands ###
