name: Create AWS Core Infra

on:
  workflow_dispatch:

jobs:
  aws-core-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Replace with your desired version

      - name: Change to Terraform directory
        run: cd ./infra

      - name: Initialize Terraform
        working-directory: ./infra
        run: terraform init

      - name: Validate Terraform configuration
        working-directory: ./infra
        run: terraform validate

      - name: Apply Terraform configuration
        working-directory: ./infra
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve
